// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address_Field_Added_To_Employer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_Field_Added_To_Employer));
        
        string IMigrationMetadata.Id
        {
            get { return "201811272018398_Address_Field_Added_To_Employer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
