// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Id_proof_for_Agency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Id_proof_for_Agency));
        
        string IMigrationMetadata.Id
        {
            get { return "201812121839576_Id_proof_for_Agency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
