// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class City_Country_String_Added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(City_Country_String_Added1));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261805005_City_Country_String_Added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
