// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Job_Offer_new_column_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Job_Offer_new_column_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201811032304140_Job_Offer_new_column_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
