// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DOB_Field_Added_To_All_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DOB_Field_Added_To_All_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050922249_DOB_Field_Added_To_All_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
