// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Country_City_And_District_Added_To_Application_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Country_City_And_District_Added_To_Application_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271945280_Country_City_And_District_Added_To_Application_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
