// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Profile_Pic_Base64Encode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Profile_Pic_Base64Encode));
        
        string IMigrationMetadata.Id
        {
            get { return "201811241933355_Profile_Pic_Base64Encode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
