// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Feedback_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Feedback_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201812201554492_User_Feedback_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
