// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Min_Age_Column_Added_To_Job_Offer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Min_Age_Column_Added_To_Job_Offer));
        
        string IMigrationMetadata.Id
        {
            get { return "201811032322443_Min_Age_Column_Added_To_Job_Offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
