// <auto-generated />
namespace HireMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Average_Star_Rating_For_JobRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Average_Star_Rating_For_JobRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201812010848100_Average_Star_Rating_For_JobRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
